name = "steam-canvas-api"
main = "index.js"
compatibility_date = "2024-09-23"
node_compat = true

[vars]
# Add non-secret environment variables here if needed

# Bindings for R2 Bucket
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "steamcanvas-assets"
